### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by tokyoincode** [scmorrison/humantranslated#2]
Hello!

I'm going to post a bunch of different logos and we can decide which one to go with during the next meeting. Please keep in mind that these are just drafts and are always subject to change. Will edit this post as much as kind with some new ideas. 

Feel free to post if you have any suggestions / ideas. 

Thanks!
# Logo 1

![htlogo01](https://cloud.githubusercontent.com/assets/6971504/5792639/d74e189a-9f65-11e4-8c68-ec72873f29a7.jpg)
# Logo 2

![htlogo02](https://cloud.githubusercontent.com/assets/6971504/5792651/264d4b90-9f67-11e4-9635-d848acbc5839.jpg)
# Logo 2 (revision)

![htlogo02rev](https://cloud.githubusercontent.com/assets/6971504/5792676/6cfbd9ac-9f68-11e4-8fa3-f8e40f9b959b.jpg)
# Logo 3 

![htlogo03](https://cloud.githubusercontent.com/assets/6971504/5792701/75b4bb08-9f69-11e4-89f1-6a8f6ec93572.jpg)

**Comment by scmorrison** [comment]
I like the 3rd one the best, but it sort of reminds me of this:

![wolfeintein](http://fc03.deviantart.net/fs71/f/2013/217/b/1/return_to_castle_wolfenstein___logo_by_lelekhd-d6gsbzn.png)

**Comment by oneilkevin** [comment]
Huh, Wolfenstien. Will come up with some more this week, have some other ideas.

**Comment by oneilkevin** [comment]
Hey! Sorry for slowing down, will add some more logos today.

**Comment by scmorrison** [comment]
Cool, I am working on the API today. I will have commits late tonight sometime.

**Comment by oneilkevin** [comment]
Cool! Did you want to have a meeting tomorrow?

**Comment by oneilkevin** [comment]
Logo 4
=========
![htlogo05](https://cloud.githubusercontent.com/assets/6971504/5887143/5a596666-a404-11e4-8742-cfc6957b09b9.png)

**Comment by oneilkevin** [comment]
Since we aren't 100% sure about the name, we could just use this as a placeholder

**Comment by scmorrison** [comment]
cool, I think it looks pretty good.

**Comment by scmorrison** [comment]
I will be around for a meeting tomorrow at 2 if you have time.

**Comment by oneilkevin** [comment]
Sure! Let's do that then, 2 PM.
