### ISSUE TITLE
Where to add directives

### ISSUE THREAD

**Issue by tokyoincode** [scmorrison/humantranslated#4]
I've looked a little bit into the headroom.js issue (http://wicky.nillia.ms/headroom.js/) and so far, have been unsuccessful. Looking at the instructions, we have to add headroom as a module.

I believe you talked about the ui-router in the last meeting, but have not found where to actually add the code. (for example: angular.module('headroom');) Tried to add the code in the ui-router files but it didn't work, sadly.

Any ideas?

Will take another look at it after dinner.

Thanks!

**Comment by scmorrison** [comment]
Hi Kevin,

Apologies for the delay. Let's work on this during the conference call. Also, Shin will be here at 2pm with computer so he will be joining us. 

The README.md update looks good. I remember you had to copy the scripts/mecab-config to your PATH somewhere (usr/bin/path) and install mecab-ipadic from source. Can you add a note about that as well?

Thanks,
Sam

**Comment by oneilkevin** [comment]
Okay, will add that!

**Comment by scmorrison** [comment]
Hey Kevin, I fixed the basic sorting for the stories, can you duplicate the functionality for Articles and figure out if there is a better way to do this? Thanks, Sam
